name: CI

on: [ push ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    services:
      custom:
        image: hello-world

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/custom-deploy-steps # Composite action
        with:
          secrets: ${{ toJSON(secrets) }}
